name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-2019    # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: test.sln
      Project_Design_Path: test\test.csproj
#      Test_Project_Path: UiPathTeam.Extensions.Tests\UiPathTeam.Extensions.Tests.csproj


    steps:
    # https://stackoverflow.com/questions/60942067/get-current-date-and-time-in-github-workflows
    - name: Get current year
      run: echo "year=$(date +'%Y')" >> $GITHUB_ENV

    - name: Application Version
      id: vers
      uses: paulhatch/semantic-version@v5.2.1
      env:
        vers: ${{steps.vers}}

    - name: print version
      run: echo $vers

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Create Build Directory
      run: mkdir _build

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Solution
      run: msbuild.exe $env:Solution_Name /verbosity:minimal /p:GeneratePackageOnBuild=false

    - name: Create the nuget package
      run: dotnet pack --configuration Debug --output "_build" --no-build

#    - name: Execute unit tests
#      run: dotnet test

#    - name: Upload nuget package
#      uses: actions/upload-artifact@v3
#      with:
#        name: nuget Package
#        path: "./_build"

#https://trstringer.com/github-actions-create-release-upload-artifacts/#:~:text=For%20the%20upload%20to%20target,it%20named%20in%20the%20release.
#https://github.com/actions/upload-release-asset
    - name: upload nuget artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./_build/test.zip
        asset_name: test.zip
        asset_content_type: application/zip
