name: Pull Request to main

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-2019

    env:
      Solution_Name: test.sln
      Project_Design_Path: test\test.csproj
#      Test_Project_Path: UiPathTeam.Extensions.Tests\UiPathTeam.Extensions.Tests.csproj


    steps:
    - name: Get current year
      run: echo "year=$(date +'%Y')" >> $GITHUB_ENV

    - name: Test1
      id: t1
      uses: Kaven-Universe/github-action-current-date-time@v1
      env:
        vers: ${{ steps.t1.outputs.milliseconds_since_epoch }}

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Create Build Directory
      run: mkdir _build

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Solution
      run: msbuild.exe $env:Solution_Name /verbosity:minimal /p:GeneratePackageOnBuild=false
      

    - name: Execute unit tests
      run: dotnet test
